import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { act, cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { KlasifikasiPicker } from './KlasifikasiPicker'

const api = vi.hoisted(() => ({ get: vi.fn() }))
vi.mock('@/services/api', () => ({ default: api }))
vi.mock('@/context/AuthContext', () => ({ useAuth: () => ({ user: { role: 'staff' } }) }))

const first = { id: 81, kode: 'TU.02.03', jenis: 'Pembinaan Kearsipan', tipe: 'fasilitatif', isSelectable: true }
const second = { id: 82, kode: 'TU.02.03', jenis: 'Jadwal Retensi Arsip', tipe: 'fasilitatif', isSelectable: true }
const retention = { id: 97, kode: 'F.VI.03', uraian: 'Penyusunan JRA', retensiAktif: '2 tahun', retensiInaktif: '3 tahun', keterangan: 'Permanen', isSelectable: true }
const suggestion = (item = retention) => ({ success: true, suggestedJRA: [item], mappings: [] })
const deferred = () => { let resolve; const promise = new Promise(done => { resolve = done }); return { promise, resolve } }

beforeEach(() => { api.get.mockReset() })
afterEach(cleanup)

describe('classification and retention selection integrity', () => {
    it('preserves the saved preview on cancellation and restores that pair when reopened', async () => {
        api.get.mockImplementation(async url => url.includes('/mapping/') ? suggestion() : { success: true, data: [first, second] })
        const onChange = vi.fn()
        render(<KlasifikasiPicker value={first.kode} selectedClassification={first} selectedRetention={retention} onChange={onChange} />)
        const trigger = screen.getByRole('button', { name: /TU.02.03 Pembinaan Kearsipan/ })
        fireEvent.click(trigger)
        const pendingDialog = await screen.findByRole('dialog')
        const pending = within(pendingDialog)
        const pendingClassification = await pending.findByRole('button', { name: /Jadwal Retensi Arsip/ })
        fireEvent.click(pendingClassification)
        fireEvent.click(await pending.findByRole('button', { name: /Penyusunan JRA/ }))
        expect(pendingClassification).toHaveAttribute('aria-pressed', 'true')
        expect(pending.getByRole('button', { name: /Pembinaan Kearsipan/ })).toHaveAttribute('aria-pressed', 'false')
        fireEvent.click(pending.getByRole('button', { name: 'Batal', exact: true }))
        await waitFor(() => expect(pendingDialog).not.toBeInTheDocument())
        expect(trigger).toHaveTextContent('Pembinaan Kearsipan')
        expect(onChange).not.toHaveBeenCalled()
        fireEvent.click(trigger)
        const reopenedDialog = await screen.findByRole('dialog')
        const reopened = within(reopenedDialog)
        expect(await reopened.findByRole('button', { name: /Pembinaan Kearsipan/ })).toHaveAttribute('aria-pressed', 'true')
        expect(await reopened.findByRole('button', { name: /Penyusunan JRA/ })).toHaveAttribute('aria-pressed', 'true')
        const confirm = reopened.getByRole('button', { name: 'Pilih', exact: true })
        await waitFor(() => expect(confirm).toBeEnabled())
        expect(onChange).not.toHaveBeenCalled()
    })

    it('confirms the selected classification by ID when official codes are identical', async () => {
        api.get.mockImplementation(async url => url.includes('/mapping/') ? suggestion() : { success: true, data: [first, second] })
        const onChange = vi.fn()
        render(<KlasifikasiPicker value={first.kode} selectedClassification={first} selectedRetention={retention} onChange={onChange} />)
        fireEvent.click(screen.getByRole('button', { name: /TU.02.03 Pembinaan Kearsipan/ }))
        const dialog = await screen.findByRole('dialog')
        const picker = within(dialog)
        const savedClassification = await picker.findByRole('button', { name: /Pembinaan Kearsipan/ })
        expect(savedClassification).toHaveAttribute('aria-pressed', 'true')
        expect(await picker.findByRole('button', { name: /Penyusunan JRA/ })).toHaveAttribute('aria-pressed', 'true')
        const confirm = picker.getByRole('button', { name: 'Pilih', exact: true })
        await waitFor(() => expect(confirm).toBeEnabled())
        const newClassification = picker.getByRole('button', { name: /Jadwal Retensi Arsip/ })
        fireEvent.click(newClassification)
        expect(newClassification).toHaveAttribute('aria-pressed', 'true')
        expect(savedClassification).toHaveAttribute('aria-pressed', 'false')
        expect(confirm).toBeDisabled()
        fireEvent.click(await picker.findByRole('button', { name: /Penyusunan JRA/ }))
        await waitFor(() => expect(confirm).toBeEnabled())
        fireEvent.click(confirm)
        expect(onChange).toHaveBeenCalledTimes(1)
        expect(onChange).toHaveBeenCalledWith('TU.02.03', second, retention)
        await waitFor(() => expect(dialog).not.toBeInTheDocument())
    })

    it('removes a saved retention preview when its controlled prop is cleared', () => {
        const onChange = vi.fn()
        const view = render(<KlasifikasiPicker value={first.kode} selectedClassification={first} selectedRetention={retention} onChange={onChange} />)
        expect(screen.getByRole('button', { name: /TU.02.03 Pembinaan Kearsipan/ })).toHaveTextContent('JRA:')
        view.rerender(<KlasifikasiPicker value={first.kode} selectedClassification={first} selectedRetention={null} onChange={onChange} />)
        expect(screen.getByRole('button', { name: /TU.02.03 Pembinaan Kearsipan/ })).not.toHaveTextContent('JRA:')
        expect(onChange).not.toHaveBeenCalled()
    })

    it('ignores delayed suggestions from an earlier classification choice', async () => {
        const older = deferred()
        const newer = deferred()
        api.get.mockResolvedValueOnce({ success: true, data: [first, second] }).mockReturnValueOnce(older.promise).mockReturnValueOnce(newer.promise)
        const onChange = vi.fn()
        render(<KlasifikasiPicker value="" onChange={onChange} />)
        fireEvent.click(screen.getByRole('button', { name: 'Pilih Klasifikasi Arsip' }))
        const dialog = await screen.findByRole('dialog')
        const picker = within(dialog)
        fireEvent.click(await picker.findByRole('button', { name: /Pembinaan Kearsipan/ }))
        await waitFor(() => expect(api.get).toHaveBeenCalledTimes(2))
        fireEvent.click(picker.getByRole('button', { name: /Jadwal Retensi Arsip/ }))
        await waitFor(() => expect(api.get).toHaveBeenCalledTimes(3))
        await act(async () => { newer.resolve(suggestion()) })
        const selectedRetention = await picker.findByRole('button', { name: /Penyusunan JRA/ })
        fireEvent.click(selectedRetention)
        await waitFor(() => expect(selectedRetention).toHaveAttribute('aria-pressed', 'true'))
        await act(async () => { older.resolve(suggestion({ ...retention, id: 98, uraian: 'Saran lama' })) })
        expect(dialog).toBeVisible()
        expect(picker.queryByRole('button', { name: /Saran lama/ })).not.toBeInTheDocument()
        expect(selectedRetention).toBeInTheDocument()
        expect(selectedRetention).toHaveAttribute('aria-pressed', 'true')
        expect(onChange).not.toHaveBeenCalled()
    })

    it('exposes recoverable errors and allows a manual JRA choice after suggestions fail', async () => {
        api.get.mockResolvedValueOnce({ success: true, data: [first] })
            .mockRejectedValueOnce(new Error('Mapping offline'))
            .mockRejectedValueOnce(new Error('Catalog offline'))
            .mockResolvedValueOnce({ success: true, data: [{ ...retention, id: 1, uraian: 'Induk', isSelectable: false }, retention] })
        const onChange = vi.fn()
        render(<KlasifikasiPicker value="" onChange={onChange} />)
        fireEvent.click(screen.getByRole('button', { name: 'Pilih Klasifikasi Arsip' }))
        fireEvent.click(await screen.findByRole('button', { name: /Pembinaan Kearsipan/ }))
        expect(await screen.findByRole('alert')).toHaveTextContent('Gagal terhubung ke server')
        fireEvent.click(screen.getByRole('button', { name: /^Semua \(/ }))
        expect(await screen.findByRole('alert')).toHaveTextContent('Gagal terhubung ke server')
        fireEvent.click(screen.getByRole('button', { name: 'Coba Lagi' }))
        const parentRule = await screen.findByRole('button', { name: /Induk/ })
        expect(parentRule).toBeVisible()
        expect(parentRule).toBeDisabled()
        fireEvent.click(parentRule)
        expect(parentRule).toHaveAttribute('aria-pressed', 'false')
        expect(screen.getByRole('button', { name: 'Pilih', exact: true })).toBeDisabled()
        fireEvent.click(await screen.findByRole('button', { name: /Penyusunan JRA/ }))
        fireEvent.click(screen.getByRole('button', { name: 'Pilih', exact: true }))
        expect(onChange).toHaveBeenCalledWith(first.kode, first, retention)
    })
})
